apiVersion: v1
kind: Service
metadata:
  name: advanced-display-relay
  labels:
    app: adr
spec:
  type: LoadBalancer
  selector:
    app: adr
  ports:
    - protocol: TCP
      name: https
      port: 443
      targetPort: 5000